### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by UzumakiAlfredo** [farshadjahanmanesh/loady#3]
Thanks for this awesome library.
Please add Carthage support or  provide a manual installation guide in the Readme file.
Thanks.

**Comment by farshadjahanmanesh** [comment]
Thank you 🙏
I will add Carthage support this week, but for manual installation, you can copy and past this folder into your project
[Loady Source files](https://github.com/farshadjahanmanesh/loady/tree/master/loady/LoadingButton)
