### ISSUE TITLE
FourPhases CurrentState

### ISSUE THREAD

**Issue by pwinterh** [farshadjahanmanesh/loady#6]
Thank you for this library. 🙂
I implemented the FourPhase Button, but i didn't find an option to access the currentState of the Button. Is there an option to get the state of the Button (loading, success, error or lock)?

**Comment by farshadjahanmanesh** [comment]
thank you, to be honest i forgot to set something like that because we change the current state ourself so we know what is the current state. can i know what is your usage?

**Comment by pwinterh** [comment]
Ok... Of course, the use case is to navigate to different ViewControllers depending on the current state of the Button. 
Something like this:
`@IBAction func pressedLoadyButton(_ sender: Any){
switch self.loadingButton.currentState {
case .success: openThisVC()
case .error: showErrorMessage()
....
}
}`

**Comment by farshadjahanmanesh** [comment]
update loady to 1.0.4, you can use currentState property which gives you a `LoadyAnimationOptions.FourPhases.Phases`.

```swift
      if case .normal(_, _ , _) = self.fourPhases.currentPhase {
               print("current phase is normal")
      }
```

**Comment by pwinterh** [comment]
Works perfectly. Thanks a lot for your amazing work!
