### ISSUE TITLE
Can't find public func when OC calls swift

### ISSUE THREAD

**Issue by sshallow** [farshadjahanmanesh/loady#9]
I'm familiar with oc, but I don't know swift, I want to use a library written in swift. I imported the header file, but when I setup in interface builder, and called the swift method, he reported an error, as follows.

[![Button i added in xib][2]][2]
[![enter image description here][3]][3]
what should I do?I don't know swift, Thank you.

  [2]: https://i.stack.imgur.com/sVRE9.png
  [3]: https://i.stack.imgur.com/oimVT.png

**Comment by farshadjahanmanesh** [comment]
@sshallow unfortunately this library is totally written in Swift and there are many items that can not represented in Objective C
